#!/usr/bin/env python3
"""
build_protocol_data.py - Compile protocol YAML to TypeScript data exports.

Reads content/<protocol>/items.yaml, content/<protocol>/reagents.yaml, and
content/<protocol>/protocol.yaml, validates them, and emits parts/protocol_data.ts
and parts/inventory_data.ts.
"""

import sys
import subprocess
import argparse
import pathlib

import yaml


def get_repo_root():
	"""Determine REPO_ROOT via git rev-parse --show-toplevel."""
	result = subprocess.run(
		['git', 'rev-parse', '--show-toplevel'],
		capture_output=True,
		text=True,
	)
	if result.returncode != 0:
		raise RuntimeError(f"Failed to find repo root: {result.stderr}")
	return pathlib.Path(result.stdout.strip())


def load_yaml_file(path):
	"""Load a YAML file and return parsed content."""
	with open(path, 'r') as f:
		return yaml.safe_load(f)


def validate_items(items, repo_root, reagents):
	"""
	Validate all items in inventory.

	Returns set of all item ids that have assets (for later SVG check).
	Raises on validation failure.
	"""
	required_roles = {
		'transfer_tool', 'aspirate_tool', 'reagent_source',
		'culture_vessel', 'cell_container', 'waste_target',
		'instrument', 'modal_tool', 'virtual_target', 'decoration'
	}
	required_scenes = {'hood', 'bench', 'overlay', 'virtual', 'none'}
	reagent_ids = set(reagents.keys())

	items_with_assets = set()

	for item_id, item_def in items.items():
		# Check required fields
		if not isinstance(item_def, dict):
			raise ValueError(f"Item '{item_id}': not a dict")
		if 'label' not in item_def:
			raise ValueError(f"Item '{item_id}': missing 'label'")
		if 'role' not in item_def:
			raise ValueError(f"Item '{item_id}': missing 'role'")
		if 'scene' not in item_def:
			raise ValueError(f"Item '{item_id}': missing 'scene'")

		# Validate role
		role = item_def['role']
		if role not in required_roles:
			raise ValueError(
				f"Item '{item_id}': role '{role}' not in {required_roles}"
			)

		# Validate scene
		scene = item_def['scene']
		if scene not in required_scenes:
			raise ValueError(
				f"Item '{item_id}': scene '{scene}' not in {required_scenes}"
			)

		# If scene is not virtual/none, asset is required
		if scene not in ('virtual', 'none'):
			if 'asset' not in item_def:
				raise ValueError(f"Item '{item_id}': asset required for scene '{scene}'")
			items_with_assets.add(item_id)
			# Note: some items are procedurally generated and may not have
			# physical SVG files in assets/equipment/, which is OK.
			# Examples: pbs_bottle, trypsin_bottle are generated by svg_assets.ts.

		# Validate liquidCapable items have capacityMl and allowedLiquids
		if item_def.get('liquidCapable'):
			if 'capacityMl' not in item_def:
				raise ValueError(
					f"Item '{item_id}': liquidCapable=true but missing capacityMl"
				)
			if 'allowedLiquids' not in item_def:
				raise ValueError(
					f"Item '{item_id}': liquidCapable=true but missing allowedLiquids"
				)
			# Validate allowedLiquids references valid reagents
			for liquid_id in item_def['allowedLiquids']:
				if liquid_id not in reagent_ids:
					raise ValueError(
						f"Item '{item_id}': allowedLiquids references unknown reagent '{liquid_id}'"
					)

		# Validate reagent_source items have contains or containsAny
		if role == 'reagent_source':
			if 'contains' not in item_def and 'containsAny' not in item_def:
				raise ValueError(
					f"Item '{item_id}': reagent_source but no 'contains' or 'containsAny'"
				)
			# Validate contains references valid reagent
			if 'contains' in item_def:
				if item_def['contains'] not in reagent_ids:
					raise ValueError(
						f"Item '{item_id}': contains references unknown reagent '{item_def['contains']}'"
					)
			# Validate containsAny references valid reagents
			if 'containsAny' in item_def:
				for liquid_id in item_def['containsAny']:
					if liquid_id not in reagent_ids:
						raise ValueError(
							f"Item '{item_id}': containsAny references unknown reagent '{liquid_id}'"
						)

	return items_with_assets


def validate_reagents(reagents):
	"""Validate all reagents in inventory. Raises on validation failure."""
	for reagent_id, reagent_def in reagents.items():
		if not isinstance(reagent_def, dict):
			raise ValueError(f"Reagent '{reagent_id}': not a dict")
		if 'label' not in reagent_def:
			raise ValueError(f"Reagent '{reagent_id}': missing 'label'")
		if 'colorKey' not in reagent_def:
			raise ValueError(f"Reagent '{reagent_id}': missing 'colorKey'")
		if 'displayColor' not in reagent_def:
			raise ValueError(f"Reagent '{reagent_id}': missing 'displayColor'")


def validate_steps(steps, items, reagents, parts, days):
	"""Validate all protocol steps. Raises on validation failure."""
	part_ids = {p['id'] for p in parts}
	day_ids = {d['id'] for d in days}
	item_ids = set(items.keys())
	reagent_ids = set(reagents.keys())
	valid_modal_owners = {'drug_treatment', 'microscope', 'incubator', 'plate_reader'}

	valid_scenes = {'hood', 'bench', 'incubator', 'microscope', 'plate_reader'}

	step_ids = set()
	first_step_id = None

	for i, step in enumerate(steps):
		if not isinstance(step, dict):
			raise ValueError(f"Step {i}: not a dict")

		step_id = step.get('id')
		if not step_id:
			raise ValueError(f"Step {i}: missing 'id'")
		if step_id in step_ids:
			raise ValueError(f"Step {i}: duplicate id '{step_id}'")
		step_ids.add(step_id)

		if first_step_id is None:
			first_step_id = step_id

		# Check required fields
		required = ['label', 'action', 'why', 'partId', 'dayId', 'stepIndex',
				'requiredItems', 'targetItems', 'scene', 'requiredAction', 'nextId']
		for field in required:
			if field not in step:
				raise ValueError(f"Step '{step_id}': missing '{field}'")

		# Validate IDs reference valid parts/days
		part_id = step['partId']
		if part_id not in part_ids:
			raise ValueError(f"Step '{step_id}': partId '{part_id}' not found")
		day_id = step['dayId']
		if day_id not in day_ids:
			raise ValueError(f"Step '{step_id}': dayId '{day_id}' not found")

		# Validate scene
		scene = step['scene']
		if scene not in valid_scenes:
			raise ValueError(f"Step '{step_id}': scene '{scene}' not in {valid_scenes}")

		# Validate requiredItems exist
		for item_id in step['requiredItems']:
			if item_id not in item_ids:
				raise ValueError(
					f"Step '{step_id}': requiredItem '{item_id}' not in inventory"
				)

		# Validate targetItems exist and have matching scene or are virtual
		for item_id in step['targetItems']:
			if item_id not in item_ids:
				raise ValueError(
					f"Step '{step_id}': targetItem '{item_id}' not in inventory"
				)
			item_def = items[item_id]
			item_scene = item_def.get('scene')
			# Allow virtual_target items or items with matching scene
			if item_def.get('role') != 'virtual_target' and item_scene != scene:
				if scene != 'bench' or item_scene not in ('bench', 'virtual'):
					if scene != 'hood' or item_scene not in ('hood', 'virtual'):
						pass  # Scene mismatch; may be OK for virtual targets

		# Validate modal field if present
		if 'modal' in step:
			modal = step['modal']
			if not isinstance(modal, dict):
				raise ValueError(f"Step '{step_id}': modal must be a dict")
			if 'owner' not in modal:
				raise ValueError(f"Step '{step_id}': modal missing 'owner'")
			if 'screen' not in modal:
				raise ValueError(f"Step '{step_id}': modal missing 'screen'")
			owner = modal['owner']
			if owner not in valid_modal_owners:
				raise ValueError(
					f"Step '{step_id}': modal.owner '{owner}' not in {valid_modal_owners}"
				)

		# Validate allowedInteractions field if present
		if 'allowedInteractions' in step:
			interactions = step['allowedInteractions']
			if not isinstance(interactions, list):
				raise ValueError(f"Step '{step_id}': allowedInteractions must be a list")
			for idx, interaction in enumerate(interactions):
				if not isinstance(interaction, dict):
					raise ValueError(
						f"Step '{step_id}': allowedInteractions[{idx}] is not a dict"
					)
				# Validate actor exists
				if 'actor' not in interaction:
					raise ValueError(
						f"Step '{step_id}': allowedInteractions[{idx}] missing 'actor'"
					)
				actor = interaction['actor']
				if actor not in item_ids:
					raise ValueError(
						f"Step '{step_id}': allowedInteractions[{idx}] actor '{actor}' not in inventory"
					)
				# Validate source exists if present
				if 'source' in interaction:
					source = interaction['source']
					if source not in item_ids:
						raise ValueError(
							f"Step '{step_id}': allowedInteractions[{idx}] source '{source}' not in inventory"
						)
					source_item = items[source]
					source_role = source_item.get('role')
					valid_source_roles = {'reagent_source', 'cell_container', 'culture_vessel'}
					if source_role not in valid_source_roles:
						raise ValueError(
							f"Step '{step_id}': allowedInteractions[{idx}] source '{source}' has role '{source_role}', expected one of {valid_source_roles}"
						)
				# Validate target exists if present
				if 'target' in interaction:
					target = interaction['target']
					if target not in item_ids:
						raise ValueError(
							f"Step '{step_id}': allowedInteractions[{idx}] target '{target}' not in inventory"
						)
					target_item = items[target]
					target_role = target_item.get('role')
					valid_target_roles = {'cell_container', 'culture_vessel', 'waste_target', 'virtual_target', 'instrument'}
					if target_role not in valid_target_roles:
						raise ValueError(
							f"Step '{step_id}': allowedInteractions[{idx}] target '{target}' has role '{target_role}', expected one of {valid_target_roles}"
						)
				# Validate liquid exists if present
				if 'liquid' in interaction:
					liquid = interaction['liquid']
					if liquid not in reagent_ids:
						raise ValueError(
							f"Step '{step_id}': allowedInteractions[{idx}] liquid '{liquid}' not in reagents"
						)
					# Validate that actor allows this liquid
					actor_item = items[actor]
					if actor_item.get('liquidCapable'):
						allowed_liquids = actor_item.get('allowedLiquids', [])
						if liquid not in allowed_liquids:
							raise ValueError(
								f"Step '{step_id}': allowedInteractions[{idx}] actor '{actor}' does not allow liquid '{liquid}'"
							)
					# Validate that source contains this liquid if source is present
					if 'source' in interaction:
						source_item = items[interaction['source']]
						source_contains = source_item.get('contains')
						source_contains_any = source_item.get('containsAny', [])
						if source_contains and source_contains != liquid:
							raise ValueError(
								f"Step '{step_id}': allowedInteractions[{idx}] source '{interaction['source']}' contains '{source_contains}', not '{liquid}'"
							)
						if source_contains_any and liquid not in source_contains_any:
							if not source_contains or source_contains != liquid:
								raise ValueError(
									f"Step '{step_id}': allowedInteractions[{idx}] source '{interaction['source']}' does not contain '{liquid}'"
								)
				# Validate volumeMl if present
				if 'volumeMl' in interaction:
					volume_ml = interaction['volumeMl']
					actor_item = items[actor]
					if actor_item.get('liquidCapable'):
						capacity = actor_item.get('capacityMl', 0)
						if volume_ml > capacity:
							raise ValueError(
								f"Step '{step_id}': allowedInteractions[{idx}] volumeMl {volume_ml} exceeds actor '{actor}' capacity {capacity}"
							)
				# Validate event matches trigger event if present
				if 'event' in interaction and 'trigger' in step:
					trigger_event = step['trigger'].get('event', '')
					# Strip prefixes like 'click:' and 'modal_ok:'
					trigger_event_stripped = trigger_event.split(':', 1)[-1] if ':' in trigger_event else trigger_event
					interaction_event = interaction['event']
					if interaction_event != trigger_event_stripped:
						raise ValueError(
							f"Step '{step_id}': allowedInteractions[{idx}] event '{interaction_event}' does not match trigger event '{trigger_event_stripped}'"
						)

	# Check nextId chain
	if not first_step_id:
		raise ValueError("No steps defined")

	visited = set()
	current_id = first_step_id
	steps_by_id = {s['id']: s for s in steps}

	while current_id is not None:
		if current_id not in steps_by_id:
			raise ValueError(f"nextId chain: step '{current_id}' not found")
		if current_id in visited:
			raise ValueError(f"nextId chain: cycle detected at '{current_id}'")
		visited.add(current_id)

		step = steps_by_id[current_id]
		next_id = step.get('nextId')
		if next_id is None:
			# Final step
			break
		current_id = next_id

	# Check that all steps are visited
	if len(visited) != len(steps):
		missing = set(steps_by_id.keys()) - visited
		raise ValueError(f"nextId chain: orphaned steps: {missing}")

	# Exactly one terminator (nextId is null)
	terminators = [s for s in steps if s.get('nextId') is None]
	if len(terminators) != 1:
		raise ValueError(f"Expected 1 terminator, found {len(terminators)}")


def ts_escape_string(s):
	"""Escape a string for TypeScript."""
	s = s.replace('\\', '\\\\')
	s = s.replace('"', '\\"')
	s = s.replace('\n', '\\n')
	s = s.replace('\r', '\\r')
	s = s.replace('\t', '\\t')
	return s


def to_ts_value(value):
	"""Convert a Python value to TypeScript literal."""
	if value is None:
		return 'null'
	elif isinstance(value, bool):
		return 'true' if value else 'false'
	elif isinstance(value, (int, float)):
		return str(value)
	elif isinstance(value, str):
		return f'"{ts_escape_string(value)}"'
	elif isinstance(value, dict):
		if not value:
			return '{}'
		items = []
		for k, v in sorted(value.items()):
			items.append(f'{k}: {to_ts_value(v)}')
		return '{ ' + ', '.join(items) + ' }'
	elif isinstance(value, list):
		if not value:
			return '[]'
		items = [to_ts_value(v) for v in value]
		return '[ ' + ', '.join(items) + ' ]'
	else:
		raise ValueError(f"Unsupported type for TS: {type(value)}")


def object_to_ts_literal(obj):
	"""Convert a dict to TypeScript object literal."""
	if not obj:
		return '{}'
	items = []
	for key, value in sorted(obj.items()):
		items.append(f'{key}: {to_ts_value(value)}')
	return '{ ' + ', '.join(items) + ' }'


def generate_protocol_data(steps, parts, days):
	"""Generate TypeScript code for protocol_data.ts."""
	lines = [
		'// AUTO-GENERATED by tools/build_protocol_data.py from content/<protocol>/*.yaml. DO NOT EDIT BY HAND.',
		'',
		'import { ProtocolStep, ProtocolPart, ProtocolDay } from "./constants";',
		'',
	]

	# Export PROTOCOL_STEPS
	lines.append('export const PROTOCOL_STEPS: readonly ProtocolStep[] = [')
	for step in steps:
		lines.append('\t{')
		for key in sorted(step.keys()):
			value = step[key]
			lines.append(f'\t\t{key}: {to_ts_value(value)},')
		lines.append('\t},')
	lines.append('];')
	lines.append('')

	# Export PROTOCOL_PARTS
	lines.append('export const PROTOCOL_PARTS: Record<string, ProtocolPart> = {')
	for part in parts:
		part_id = part['id']
		lines.append(f'\t{part_id}: {object_to_ts_literal(part)},')
	lines.append('};')
	lines.append('')

	# Export PROTOCOL_DAYS
	lines.append('export const PROTOCOL_DAYS: Record<string, ProtocolDay> = {')
	for day in days:
		day_id = day['id']
		lines.append(f'\t{day_id}: {object_to_ts_literal(day)},')
	lines.append('};')
	lines.append('')

	return '\n'.join(lines)


def generate_inventory_data(items, reagents):
	"""Generate TypeScript code for inventory_data.ts."""
	lines = [
		'// AUTO-GENERATED by tools/build_protocol_data.py from content/<protocol>/*.yaml. DO NOT EDIT BY HAND.',
		'',
		'export interface InventoryItem {',
		'\tlabel: string;',
		'\trole: string;',
		'\tscene: string;',
		'\tasset?: string;',
		'\tliquidCapable?: boolean;',
		'\tcapacityMl?: number;',
		'\tallowedLiquids?: string[];',
		'\tcontains?: string;',
		'\tcontainsAny?: string[];',
		'\tvisualOnly?: boolean;',
		'}',
		'',
		'export interface InventoryReagent {',
		'\tlabel: string;',
		'\tcolorKey: string;',
		'\tdisplayColor: string;',
		'}',
		'',
		'export const EQUIPMENT: Record<string, InventoryItem> = {',
	]

	for item_id, item_def in items.items():
		lines.append(f'\t{item_id}: {object_to_ts_literal(item_def)},')
	lines.append('};')
	lines.append('')

	lines.append('export const REAGENTS: Record<string, InventoryReagent> = {')
	for reagent_id, reagent_def in reagents.items():
		lines.append(f'\t{reagent_id}: {object_to_ts_literal(reagent_def)},')
	lines.append('};')
	lines.append('')

	return '\n'.join(lines)


def main():
	"""Main entry point."""
	parser = argparse.ArgumentParser(
		description='Compile protocol YAML to TypeScript data exports.'
	)
	parser.add_argument(
		'--protocol',
		default='cell_culture',
		help='Protocol name for multi-protocol support (default: cell_culture).',
	)
	parser.add_argument(
		'--check',
		action='store_true',
		help='Validate only; do not write output files.',
	)
	args = parser.parse_args()

	repo_root = get_repo_root()

	# Load YAML files
	protocol_dir = repo_root / 'content' / args.protocol
	if not protocol_dir.is_dir():
		print(f"Error: Protocol directory not found: {protocol_dir}", file=sys.stderr)
		return 1

	items_path = protocol_dir / 'items.yaml'
	reagents_path = protocol_dir / 'reagents.yaml'
	protocol_path = protocol_dir / 'protocol.yaml'

	# Verify files exist
	for path in [items_path, reagents_path, protocol_path]:
		if not path.exists():
			print(f"Error: Missing file: {path}", file=sys.stderr)
			return 1

	items_data = load_yaml_file(items_path)
	reagents_data = load_yaml_file(reagents_path)
	protocol = load_yaml_file(protocol_path)

	items = items_data.get('items', {})
	reagents = reagents_data.get('reagents', {})
	parts = protocol.get('parts', [])
	days = protocol.get('days', [])
	steps = protocol.get('steps', [])

	# Validate
	validate_reagents(reagents)
	validate_items(items, repo_root, reagents)
	validate_steps(steps, items, reagents, parts, days)

	if args.check:
		print("Validation passed.")
		return 0

	# Generate and write output files
	protocol_data_ts = generate_protocol_data(steps, parts, days)
	inventory_data_ts = generate_inventory_data(items, reagents)

	protocol_data_path = repo_root / 'parts' / 'protocol_data.ts'
	inventory_data_path = repo_root / 'parts' / 'inventory_data.ts'

	with open(protocol_data_path, 'w') as f:
		f.write(protocol_data_ts)
	with open(inventory_data_path, 'w') as f:
		f.write(inventory_data_ts)
	print(f"Generated {protocol_data_path}")
	print(f"Generated {inventory_data_path}")

	return 0


if __name__ == '__main__':
	sys.exit(main())
